### ISSUE TITLE
dynamic/custom websocket

### ISSUE THREAD

**Issue by hitchhooker** [tien/reactive-dot#269]
seems like websocket requires descriptor to be set instead of being dynamic.

what's the ideal way of creating custom websocket field for frontend with reactive-dot?
![image](https://github.com/user-attachments/assets/9d485bc7-b97d-4713-be09-c5b1aa1b19dc)

**Comment by tien** [comment]
Apologies, I've thought about doing this before with tien/dot-console#5. But I haven't come up with an API that I'm completely happy with. Will look into it this week 👌

**Comment by tien** [comment]
Just want to give an update that I haven't forgot about this yet. Simply haven't been able to come up with an API that's not horrible yet :(
