### ISSUE TITLE
WalletConnect `requiredNamespaces` optionnal (and so should be `chainIds`)

### ISSUE THREAD

**Issue by Tbaut** [tien/reactive-dot#399]
In dot-connect, I have to passe `chainIds` and if I omit it, or pass it an empty array instead I get an error.
> Unsupported chains. connect() requiredNamespaces, chains must be defined as "namespace:chainId" e.g. "eip155:1": {...} in the namespace key OR as an array of CAIP-2 chainIds e.g. eip155: { chains: ["eip155:1", "eip155:5"] }

In the WalletConnect types, you can see that `requiredNamespaces` and `optionalNamespaces` too. One of the 2 should definitely not be empty. Here: https://github.com/WalletConnect/walletconnect-monorepo/blob/74bb304a452725e36e0fcd70aafcb1a0f12d31ee/packages/types/src/sign-client/engine.ts#L60

From my experience, Dapps like Hydration have only passed a long list of optional namespaces, e.g https://github.com/galacticcouncil/hydration-ui/blob/master/src/sections/web3-connect/wallets/WalletConnect.ts#L274 and this is what I would like to do in Delegit too. I support many chains and don't want the wallet provider to have to support all of them. E.g Delegit supports Polkadot, Kusama, and Paseo, whereas my wallet provider would have Polkadot, Kusama, and Westend. Then just because WC requires Paseo, and the provider doesn't have it, the WC connection would fail. This is something that the wallet provider has to check, not the Dapp.

**Comment by tien** [comment]
Yeah, I remember it used to be the case that you can pass an empty array. Apparently, doing so now will throw an error :p
